version: '3.1'

services:

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data